// <auto-generated>  This file is generated by CmsModelsGenerator. Do not edit manually. </auto-generated>
namespace Constants
{
    public static class Models
    {

        // --- Ungrouped ---
        public const string Enemy1 = "CMS/Prefabs/Models/Enemy 1";
        public const string Enemy2 = "CMS/Prefabs/Models/Enemy 2";
    }
}
